# Generated by Django 3.0.7 on 2020-06-05 13:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hordak", "0027_trigger_update_full_account_codes_effective"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundManager",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=251)),
                ("fund", models.UUIDField()),
                ("fund_number", models.PositiveIntegerField()),
                ("hurdle", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hordak.Account"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                ("date", models.DateField()),
                ("company", models.UUIDField()),
                (
                    "total_loan_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("total_collateral_shares", models.PositiveIntegerField()),
                ("interest_loan", models.DecimalField(decimal_places=4, max_digits=8)),
                (
                    "interest_equity",
                    models.DecimalField(decimal_places=4, max_digits=8),
                ),
                ("last_booking_interest", models.DateTimeField(null=True)),
                ("last_booking_equity_valuation", models.DateTimeField(null=True)),
                (
                    "eq_account_stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eq_account_stock",
                        to="hordak.Account",
                    ),
                ),
                (
                    "eq_account_value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eq_account_value",
                        to="hordak.Account",
                    ),
                ),
                (
                    "eq_unrealized_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eq_unrealized_account",
                        to="hordak.Account",
                    ),
                ),
                (
                    "fi_account_stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fi_account_stock",
                        to="hordak.Account",
                    ),
                ),
                (
                    "fi_account_value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fi_account_value",
                        to="hordak.Account",
                    ),
                ),
                (
                    "fi_unrealized_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fi_unrealized_account",
                        to="hordak.Account",
                    ),
                ),
                (
                    "fund_manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fund_accounting_app.FundManager",
                    ),
                ),
            ],
        ),
    ]
