# Generated by Django 3.0.7 on 2020-06-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund_accounting_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='company_name',
            field=models.CharField(default='Test', max_length=200),
            preserve_default=False,
        ),
    ]
