# Generated by Django 3.0.6 on 2020-06-03 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fund_accounting_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='account',
        ),
    ]
