# Generated by Django 3.0.6 on 2020-06-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund_accounting_app', '0002_remove_deal_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundmanager',
            name='fund_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
